### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by awmartin** [tfoldi/go2-webrtc#17]
I'm running a Go2 Pro at firmware v1.0.22. I've obtained an accessToken via curl to the /login/email endpoint and have the go2-webrtc web app running. I provide the accessToken and the IP address for the robot in the interface.

However, any attempt to connect to the Go2 fails. I can ping the robot at its IP address, but I get a connection refused error when clicking Connect.

```
Added /home/awmartin/workspace/go2-webrtc/python to sys.path
Serving on port 8081
127.0.0.1 - - [08/Dec/2024 17:35:42] "GET / HTTP/1.1" 304 -
ERROR:root:An error occurred: HTTPConnectionPool(host='192.168.0.169', port=9991): Max retries exceeded with url: /con_notify (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d39f2c58da0>: Failed to establish a new connection: [Errno 111] Connection refused'))
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 53750)
Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/home/awmartin/workspace/go2-webrtc/javascript/./server.py", line 75, in do_POST
    response_data = go2_webrtc.Go2Connection.get_peer_answer(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/awmartin/workspace/go2-webrtc/python/go2_webrtc/go2_connection.py", line 294, in get_peer_answer
    raise ValueError(
ValueError: Failed to receive initial public key response with new method.
----------------------------------------
```

Ubuntu 24.04. Python 3.12.3. Any insights would be helpful!

**Comment by tfoldi** [comment]
it supposed to first try to connect with the old method on port 8081. from the logs it seems it jumped directly to the new firmware method. 

can you try this commit tree: https://github.com/tfoldi/go2-webrtc/tree/47f6d54  ?
